import { Inter } from "next/font/google";
import "./globals.css";
import LoadingBar from "./components/LoadingBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Facebook Helpdesk",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <LoadingBar />
        {children}
      </body>
    </html>
  );
}
